networks:
  lan-net:   #faster connection b/w device-edge
    driver: bridge

  wan-net:    #slower connection b/w server-edge 
    driver: bridge

services:
# mqtt-broker:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    restart: unless-stopped
    networks:
      - wan-net
      - lan-net
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosq/config:/mosquitto/config
      - ./mosq/data:/mosq/data
      - ./mosq/log:/mosq/log

  # edgeNode configuration
  edge_node:
    build: ./edgeNode
    depends_on:
      - mqtt
    # restart: on-failure
    networks:
      - wan-net
      - lan-net
    environment:
      - MQTT_BROKER_HOST=mqtt
      - EDGE_ID=edgeNode_1
      - LOG_LEVEL=INFO
      - DEVICE_PSK=my_super_secret_32_byte_aes_key!
  #resources limit for edge note
    # cpus: '0.50'
    # memory: 256M

  #server configuration
  server:
    build: ./server
    depends_on:
      - mqtt
    networks:
      - lan-net
    # restart: on-failure
    environment:
      - MQTT_BROKER_HOST=mqtt
      - LOG_LEVEL=INFO
    volumes:
      - ./server/server_data:/app/data

    ##device configuration
  device:
    build: ./device
    networks:
      - lan-net
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER_HOST=mqtt
      - NUM_DEVICES=10
      - DEVICE_PSK=my_super_secret_32_byte_aes_key!
