version: '3.8'

services:
  # The MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2
    networks:
      - local-net
      - wan-net
    ports:
      - "1883:1883"

  # The Central Server
  server:
    build: ./server
    networks:
      - wan-net
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - LOG_LEVEL=INFO
    volumes:
      - ./server/server_data:/app/data # Persists the database

  # The Edge Node
  edge_node:
    build: ./edge_node
    networks:
      - local-net
      - wan-net
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - LOG_LEVEL=INFO
      - EDGE_ID=edge_node_main_ward
      # This is the pre-shared key for communicating with local devices
      - DEVICE_PSK=my_super_secret_32_byte_aes_key!
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  # This container adds latency and limits bandwidth on the wan-net
  wan-emulator:
    image: clumsy/clumsy
    cap_add:
      - NET_ADMIN
    networks:
      - wan-net
    command: --filter "not dst port 22" --latency 150 --latency-distro normal --bandwidth 2Mbps

networks:
  # Fast network for local communication (Device <-> Edge)
  local-net:
    driver: bridge

  # Slower, impaired network for internet communication (Edge <-> Server)
  wan-net:
    driver: bridge